[Service]
Host = "edgex-device-modbus"
Port = 49991
ConnectRetries = 3 
Labels = ["modbus"]
OpenMsg = "device modbus started"
Timeout = 5000
EnableAsyncReadings = true
AsyncBufferSize = 16

[Registry]
Host = "edgex-core-consul"
Port = 8500
CheckInterval = "10s"
FailLimit = 3 
FailWaitTime = 10
Type = "consul"

[Clients]
  [Clients.Data]
  Name = "edgex-core-data"
  Protocol = "http"
  Host = "edgex-core-data"
  Port = 48080
  Timeout = 50000

  [Clients.Metadata]
  Name = "edgex-core-metadata"
  Protocol = "http"
  Host = "edgex-core-metadata"
  Port = 48081
  Timeout = 50000

  [Clients.Logging]
  Name = "edgex-support-logging"
  Protocol = "http"
  Host = "edgex-support-logging"
  Port = 48061

[Writable]
LogLevel = "INFO"

[Logging]
EnableRemote = false
File = "./device-modbus.log"

[Device]
  DataTransform = true
  InitCmd = ""
  InitCmdArgs = ""
  MaxCmdOps = 128
  MaxCmdValueLen = 256
  RemoveCmd = ""
  RemoveCmdArgs = ""
  ProfilesDir = "/custom-config"

# Pre-define Devices
[[DeviceList]]
  Name = "Modbus-RTU-Device"
  Profile = "TEST RTU Profile"
  Description = "This device is a product for monitoring and controlling digital inputs and outputs over a LAN."
  labels = [ "Air conditioner","modbus RTU" ]
  [DeviceList.Protocols]
    [DeviceList.Protocols.modbus-rtu]
       Address = "/dev/ttyUSB1"
       BaudRate = "9600"
       DataBits = "8"
       StopBits = "2"
       Parity = "N"
       UnitID = "1"
  [[DeviceList.AutoEvents]]
    Resource = "PresentValue"
    OnChange = true
    Frequency = "1s"
