version: "3"

services:
  app:
    restart: always
    build: . 
    command: ["python3", "manage.py", "runserver", "0.0.0.0:8000"]
    volumes:
      - .:/code
    ports:
      - "8093:8000"
    depends_on:
      - db


  db:
    image: mysql:latest
    command: mysqld --default-authentication-plugin=mysql_native_password
    volumes:
      - "./mysql:/var/lib/mysql"
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=12345
      - MYSQL_DATABASE=django_app
      - MYSQL_USER=django_app
      - MYSQL_PASSWORD=12345

#  elasticsearch:
#    image: docker.elastic.co/elasticsearch/elasticsearch:7.2.0
#    ports:
#      - "9200:9200"
#      - "9300:9300"




#  nginx:
#    image: nginx:latest
#    ports:
#      - "3000:8000"
#    volumes:
#      - static-volume:/code/static
#      - ./config/nginx:/etc/nginx/conf.d
#    depends_on:
#      - app
#    networks:
#      - web_network

#networks:
#  web_network:
#    driver: bridge
#  db_network:
#    driver: bridge
#
#volumes:
#  static-volume:

